name: OzLaw AI - Ingest and Test Legal Documents

on:
  push:
    paths:
      - 'data/**'
      - 'backend/legal_ai/document_ingest.py'
      - 'requirements.txt'
      - 'backend/legal_ai/rag_pipeline.py'
      - 'tests/**'

jobs:
  ingest-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up .env for OzLaw AI
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Ingest legal documents
        run: python backend/legal_ai/document_ingest.py

      - name: Run OzLaw AI RAG pipeline tests
        run: python tests/test_rag_pipeline.py

      - name: Run Django system check
        run: |
          cd backend
          python manage.py check 